#!/usr/bin/env bash
set -euo pipefail

echo "[entrypoint] pid=$$ starting as $(id -un) ($(id))"

# Reduce a public-host value to bare hostname for Traefik allowlists (HTTP(S) URL or host:port).
normalize_paperclip_hostname() {
    local raw="${1:-}"
    raw="$(printf '%s' "$raw" | tr -d '\r\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if [ -z "$raw" ]; then
        printf ''
        return 0
    fi
    raw="${raw#https://}"
    raw="${raw#http://}"
    raw="${raw%%/*}"
    raw="${raw%%:*}"
    printf '%s' "$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]')"
}

export PAPERCLIP_HOME="${PAPERCLIP_HOME:-/data/paperclip}"
export HERMES_HOME="${HERMES_HOME:-/data/hermes}"
# `bind` (loopback|lan|tailnet) is paperclipai's reachability preset, baked in
# at onboard time. The default `loopback` binds to 127.0.0.1 only and makes
# the app unreachable from outside the container, so we default to `lan`.
export PAPERCLIP_BIND="${PAPERCLIP_BIND:-lan}"
# `exposure` (public|private) controls whether paperclipai enforces a hostname
# allowlist. `public` accepts any Host header (deploymentMode=authenticated
# still gates access via login). `private` enforces `allowedHostnames` and
# requires registering each public hostname via `paperclipai allowed-hostname`.
# For Traefik-fronted deploys, `public` is the right default — auth is still on.
export PAPERCLIP_EXPOSURE="${PAPERCLIP_EXPOSURE:-public}"
# README/Dokploy sometimes use IP_ADDRESS; accept as alias for PAPERCLIP_DOMAIN.
export PAPERCLIP_DOMAIN="${PAPERCLIP_DOMAIN:-${IP_ADDRESS:-}}"
export PAPERCLIP_DOMAIN="$(normalize_paperclip_hostname "$PAPERCLIP_DOMAIN")"
#
# Paperclip's Node server (@paperclipai/server) honors these names — NOT `PAPERCLIP_EXPOSURE`.
# Mirror our compose-friendly var into upstream env for the supervised `paperclipai run`:
export PAPERCLIP_DEPLOYMENT_EXPOSURE="${PAPERCLIP_DEPLOYMENT_EXPOSURE:-${PAPERCLIP_EXPOSURE:-public}}"
# When you set PAPERCLIP_DOMAIN, push it into Paperclip's allowlist regardless of exposure
# (`public` skips enforcement; harmless). For `private`, this avoids relying on flaky JSON edits.
if [ -n "${PAPERCLIP_DOMAIN:-}" ]; then
    export PAPERCLIP_ALLOWED_HOSTNAMES="${PAPERCLIP_ALLOWED_HOSTNAMES:-$PAPERCLIP_DOMAIN}"
fi
#
# authenticated + deploymentExposure `public` requires an explicit HTTPS (or HTTP) origin.
# Dokploy terminates TLS → default to https://<domain>; override anytime with PAPERCLIP_PUBLIC_URL.
if [ "${PAPERCLIP_DEPLOYMENT_EXPOSURE:-}" = "public" ] \
    && [ -n "${PAPERCLIP_DOMAIN:-}" ] \
    && [ -z "${PAPERCLIP_PUBLIC_URL:-}${PAPERCLIP_AUTH_PUBLIC_BASE_URL:-}${BETTER_AUTH_URL:-}${BETTER_AUTH_BASE_URL:-}" ]; then
    export PAPERCLIP_PUBLIC_URL="https://${PAPERCLIP_DOMAIN}"
fi

mkdir -p "${PAPERCLIP_HOME}" "${HERMES_HOME}"

# ---------------------------------------------------------------------------
# Hermes config + skill seeding.
# ---------------------------------------------------------------------------
if [ ! -f "${HERMES_HOME}/config.yaml" ]; then
    echo "[entrypoint] seeding ${HERMES_HOME}/config.yaml from /etc/hermes/config.yaml"
    cp /etc/hermes/config.yaml "${HERMES_HOME}/config.yaml"
fi

{
    echo "# Generated by entrypoint.sh from container env on $(date -u +%FT%TZ)"
    [ -n "${OPENROUTER_API_KEY:-}" ]      && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
    [ -n "${ANTHROPIC_API_KEY:-}" ]       && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
    [ -n "${OPENAI_API_KEY:-}" ]          && echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
    [ -n "${GOOGLE_API_KEY:-}" ]          && echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}"
    [ -n "${BROWSER_USE_API_KEY:-}" ]     && echo "BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}"
    [ -n "${BROWSERBASE_API_KEY:-}" ]     && echo "BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY}"
    [ -n "${BROWSERBASE_PROJECT_ID:-}" ]  && echo "BROWSERBASE_PROJECT_ID=${BROWSERBASE_PROJECT_ID}"
} >"${HERMES_HOME}/.env"

if [ -n "${HERMES_MODEL:-}" ]; then
    echo "[entrypoint] setting hermes model.default = ${HERMES_MODEL}"
    sed -i -E "s|^(  default:).*|\1 \"${HERMES_MODEL}\"|" "${HERMES_HOME}/config.yaml"
fi

mkdir -p "${HERMES_HOME}/skills/browser-harness"
ln -sf /opt/browser-harness/SKILL.md            "${HERMES_HOME}/skills/browser-harness/SKILL.md"
ln -sf /opt/browser-harness/interaction-skills  "${HERMES_HOME}/skills/browser-harness/interaction-skills"
ln -sf /opt/browser-harness/domain-skills       "${HERMES_HOME}/skills/browser-harness/domain-skills"

chown -R node:node "${PAPERCLIP_HOME}" "${HERMES_HOME}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Dispatch on CMD.
# ---------------------------------------------------------------------------
case "${1:-paperclip}" in
    paperclip)
        # First boot only: paperclipai onboard initialises the data dir + db.
        # Run as node since the bundled postgres refuses to start as root.
        if [ ! -d "${PAPERCLIP_HOME}/instances" ]; then
            echo "[entrypoint] first boot — paperclipai onboard --yes --bind ${PAPERCLIP_BIND} --data-dir ${PAPERCLIP_HOME}"
            su -s /bin/bash node -c "
                export HOME='${PAPERCLIP_HOME}' \
                       PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                       HERMES_HOME='${HERMES_HOME}' \
                       PATH='${PATH}'
                paperclipai onboard --yes --bind '${PAPERCLIP_BIND}' --data-dir '${PAPERCLIP_HOME}'
            " || echo "[entrypoint] WARNING: onboard exited non-zero"
        fi

        # Do NOT sed-edit server.exposure in config.json. authenticated + exposure=public must
        # also satisfy auth.publicBaseUrl in Paperclip's Zod schema; mutating exposure alone breaks
        # `paperclipai allowed-hostname` (CLI readConfig) while the server stays on private/default.
        # Instead we set `PAPERCLIP_DEPLOYMENT_EXPOSURE`, `PAPERCLIP_ALLOWED_HOSTNAMES`, and
        # `PAPERCLIP_PUBLIC_URL` from env above — upstream Paperclip merges those at runtime.

        CFG="${PAPERCLIP_HOME}/instances/default/config.json"

        # Always register PAPERCLIP_DOMAIN in the allowlist if set. This is the
        # canonical fix paperclipai's own error message recommends, and it works
        # regardless of exposure mode — harmless in public, required in private.
        # We do this every boot so a stale volume from an earlier deploy still
        # gets the right hostname registered without manual intervention.
        if [ -n "${PAPERCLIP_DOMAIN:-}" ]; then
            echo "[entrypoint] registering allowed-hostname '${PAPERCLIP_DOMAIN}'"
            su -s /bin/bash node -c "
                export HOME='${PAPERCLIP_HOME}' \
                       PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                       PATH='${PATH}'
                paperclipai allowed-hostname --data-dir '${PAPERCLIP_HOME}' '${PAPERCLIP_DOMAIN}'
            " || echo "[entrypoint] WARNING: allowed-hostname registration failed"
        fi

        echo "[entrypoint] Paperclip runtime env:"
        echo "[entrypoint]   PAPERCLIP_DEPLOYMENT_EXPOSURE=${PAPERCLIP_DEPLOYMENT_EXPOSURE:-}"
        echo "[entrypoint]   PAPERCLIP_DOMAIN=${PAPERCLIP_DOMAIN:-}"
        echo "[entrypoint]   PAPERCLIP_ALLOWED_HOSTNAMES=${PAPERCLIP_ALLOWED_HOSTNAMES:-}"
        echo "[entrypoint]   PAPERCLIP_PUBLIC_URL=${PAPERCLIP_PUBLIC_URL:-}"

        # On-disk exposure may remain private — the server overlays via PAPERCLIP_DEPLOYMENT_EXPOSURE.
        if [ -f "$CFG" ]; then
            echo "[entrypoint] config.json stored server fields (merged with runtime env above):"
            grep -E '"exposure"|"allowedHostnames"' "$CFG" | sed 's/^/[entrypoint]   /'
        fi

        echo "[entrypoint] starting paperclipai run --bind ${PAPERCLIP_BIND} --data-dir ${PAPERCLIP_HOME} as node on :3100"
        # Preserve full container env unless we override HOME — Paperclip merges
        # PAPERCLIP_ALLOWED_HOSTNAMES / PAPERCLIP_DEPLOYMENT_EXPOSURE / PAPERCLIP_PUBLIC_URL
        # from exported vars above (do not blank unrelated secrets with empty `export` here).
        exec su -s /bin/bash node -c "
            export HOME='${PAPERCLIP_HOME}' \
                   PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                   HERMES_HOME='${HERMES_HOME}' \
                   PATH='${PATH}'
            exec paperclipai run --bind '${PAPERCLIP_BIND}' --data-dir '${PAPERCLIP_HOME}'
        "
        ;;
    hermes)
        # Interactive hermes CLI as node user — sees the same config + skills
        # paperclipai would.
        shift
        exec su -s /bin/bash node -c "
            export HOME='${HERMES_HOME}' \
                   HERMES_HOME='${HERMES_HOME}' \
                   PATH='${PATH}'
            exec hermes $*
        "
        ;;
    *)
        exec "$@"
        ;;
esac
