#!/usr/bin/env bash
set -euo pipefail

echo "[entrypoint] pid=$$ starting as $(id -un) ($(id))"

export PAPERCLIP_HOME="${PAPERCLIP_HOME:-/data/paperclip}"
export HERMES_HOME="${HERMES_HOME:-/data/hermes}"
# paperclipai uses --bind <mode> (loopback|lan|tailnet), set at onboard time,
# to control which interfaces it listens on. The default `loopback` binds to
# 127.0.0.1 only and makes the app unreachable from outside the container —
# which is wrong for any networked deployment, so we default to `lan`.
export PAPERCLIP_BIND="${PAPERCLIP_BIND:-lan}"

mkdir -p "${PAPERCLIP_HOME}" "${HERMES_HOME}"

# ---------------------------------------------------------------------------
# Seed Hermes config + skills into the persistent volume on first boot.
# Subsequent boots leave config.yaml alone (so hand-edits survive) but always
# refresh .env from container env vars and re-link the browser-harness skill
# (idempotent symlinks).
# ---------------------------------------------------------------------------
if [ ! -f "${HERMES_HOME}/config.yaml" ]; then
    echo "[entrypoint] seeding ${HERMES_HOME}/config.yaml from /etc/hermes/config.yaml"
    cp /etc/hermes/config.yaml "${HERMES_HOME}/config.yaml"
fi

# Always write .env from current Dokploy-supplied env vars. Only set keys
# get written, so unset ones stay absent rather than empty strings.
{
    echo "# Generated by entrypoint.sh from container env on $(date -u +%FT%TZ)"
    [ -n "${OPENROUTER_API_KEY:-}" ]      && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
    [ -n "${ANTHROPIC_API_KEY:-}" ]       && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
    [ -n "${OPENAI_API_KEY:-}" ]          && echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
    [ -n "${GOOGLE_API_KEY:-}" ]          && echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}"
    [ -n "${BROWSER_USE_API_KEY:-}" ]     && echo "BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}"
    [ -n "${BROWSERBASE_API_KEY:-}" ]     && echo "BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY}"
    [ -n "${BROWSERBASE_PROJECT_ID:-}" ]  && echo "BROWSERBASE_PROJECT_ID=${BROWSERBASE_PROJECT_ID}"
} >"${HERMES_HOME}/.env"

# Patch model.default if HERMES_MODEL is set. Matches the first
# `default: "..."` line under the `model:` block.
if [ -n "${HERMES_MODEL:-}" ]; then
    echo "[entrypoint] setting hermes model.default = ${HERMES_MODEL}"
    sed -i -E "s|^(  default:).*|\1 \"${HERMES_MODEL}\"|" "${HERMES_HOME}/config.yaml"
fi

# Re-link browser-harness skill into $HERMES_HOME/skills (idempotent).
mkdir -p "${HERMES_HOME}/skills/browser-harness"
ln -sf /opt/browser-harness/SKILL.md            "${HERMES_HOME}/skills/browser-harness/SKILL.md"
ln -sf /opt/browser-harness/interaction-skills  "${HERMES_HOME}/skills/browser-harness/interaction-skills"
ln -sf /opt/browser-harness/domain-skills       "${HERMES_HOME}/skills/browser-harness/domain-skills"

# Make sure node user owns its data dirs after we touched them as root.
chown -R node:node "${PAPERCLIP_HOME}" "${HERMES_HOME}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Dispatch on CMD. Default is `paperclip` (web service). Pass `hermes` for
# an interactive hermes session, or any other command to run it verbatim.
# ---------------------------------------------------------------------------
case "${1:-paperclip}" in
    paperclip)
        # First boot: paperclipai onboard initialises its data dir + db schema.
        # Run as node since the embedded postgres refuses to come up as root,
        # and onboard touches the same files run() will read. We pass
        # --bind ${PAPERCLIP_BIND} so the reachability preset is set up-front,
        # not stuck on the loopback default.
        if [ ! -d "${PAPERCLIP_HOME}/instances" ]; then
            echo "[entrypoint] first boot — running paperclipai onboard --yes --bind ${PAPERCLIP_BIND} as node"
            su -s /bin/bash node -c "
                export HOME='${PAPERCLIP_HOME}' \
                       PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                       HERMES_HOME='${HERMES_HOME}' \
                       PATH='${PATH}'
                paperclipai onboard --yes --bind '${PAPERCLIP_BIND}'
            " || echo "[entrypoint] WARNING: onboard exited non-zero"
        fi

        # Optional: register a public hostname/IP as allowed origin so the
        # paperclip web UI accepts requests from outside localhost.
        if [ -n "${IP_ADDRESS:-}" ]; then
            echo "[entrypoint] registering allowed-hostname '${IP_ADDRESS}'"
            su -s /bin/bash node -c "
                export HOME='${PAPERCLIP_HOME}' \
                       PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                       HERMES_HOME='${HERMES_HOME}' \
                       PATH='${PATH}'
                paperclipai allowed-hostname '${IP_ADDRESS}'
            " || echo "[entrypoint] WARNING: allowed-hostname registration failed"
        fi

        echo "[entrypoint] starting paperclipai run --bind ${PAPERCLIP_BIND} as node on :3100"
        exec su -s /bin/bash node -c "
            export HOME='${PAPERCLIP_HOME}' \
                   PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                   HERMES_HOME='${HERMES_HOME}' \
                   PATH='${PATH}'
            exec paperclipai run --bind '${PAPERCLIP_BIND}'
        "
        ;;
    hermes)
        # Drop into a hermes CLI session as node user so it sees the same
        # config + skill tree paperclipai would.
        shift
        exec su -s /bin/bash node -c "
            export HOME='${HERMES_HOME}' \
                   HERMES_HOME='${HERMES_HOME}' \
                   PATH='${PATH}'
            exec hermes $*
        "
        ;;
    *)
        # Run an arbitrary command verbatim (e.g. for `docker exec` or debugging).
        exec "$@"
        ;;
esac
