#!/usr/bin/env bash
set -euo pipefail

echo "[entrypoint] pid=$$ starting as $(id -un) ($(id))"

export PAPERCLIP_HOME="${PAPERCLIP_HOME:-/data/paperclip}"
export HERMES_HOME="${HERMES_HOME:-/data/hermes}"
# `bind` (loopback|lan|tailnet) is paperclipai's reachability preset, baked in
# at onboard time. The default `loopback` binds to 127.0.0.1 only and makes
# the app unreachable from outside the container, so we default to `lan`.
export PAPERCLIP_BIND="${PAPERCLIP_BIND:-lan}"
# `exposure` (public|private) controls whether paperclipai enforces a hostname
# allowlist. `public` accepts any Host header (deploymentMode=authenticated
# still gates access via login). `private` enforces `allowedHostnames` and
# requires registering each public hostname via `paperclipai allowed-hostname`.
# For Traefik-fronted deploys, `public` is the right default — auth is still on.
export PAPERCLIP_EXPOSURE="${PAPERCLIP_EXPOSURE:-public}"
# Public hostname Traefik routes to this service. Used to register the
# allowed-hostname on every boot so private-mode allowlist always accepts it.
export PAPERCLIP_DOMAIN="${PAPERCLIP_DOMAIN:-}"

mkdir -p "${PAPERCLIP_HOME}" "${HERMES_HOME}"

# ---------------------------------------------------------------------------
# Hermes config + skill seeding.
# ---------------------------------------------------------------------------
if [ ! -f "${HERMES_HOME}/config.yaml" ]; then
    echo "[entrypoint] seeding ${HERMES_HOME}/config.yaml from /etc/hermes/config.yaml"
    cp /etc/hermes/config.yaml "${HERMES_HOME}/config.yaml"
fi

{
    echo "# Generated by entrypoint.sh from container env on $(date -u +%FT%TZ)"
    [ -n "${OPENROUTER_API_KEY:-}" ]      && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
    [ -n "${ANTHROPIC_API_KEY:-}" ]       && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
    [ -n "${OPENAI_API_KEY:-}" ]          && echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
    [ -n "${GOOGLE_API_KEY:-}" ]          && echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}"
    [ -n "${BROWSER_USE_API_KEY:-}" ]     && echo "BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}"
    [ -n "${BROWSERBASE_API_KEY:-}" ]     && echo "BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY}"
    [ -n "${BROWSERBASE_PROJECT_ID:-}" ]  && echo "BROWSERBASE_PROJECT_ID=${BROWSERBASE_PROJECT_ID}"
} >"${HERMES_HOME}/.env"

if [ -n "${HERMES_MODEL:-}" ]; then
    echo "[entrypoint] setting hermes model.default = ${HERMES_MODEL}"
    sed -i -E "s|^(  default:).*|\1 \"${HERMES_MODEL}\"|" "${HERMES_HOME}/config.yaml"
fi

mkdir -p "${HERMES_HOME}/skills/browser-harness"
ln -sf /opt/browser-harness/SKILL.md            "${HERMES_HOME}/skills/browser-harness/SKILL.md"
ln -sf /opt/browser-harness/interaction-skills  "${HERMES_HOME}/skills/browser-harness/interaction-skills"
ln -sf /opt/browser-harness/domain-skills       "${HERMES_HOME}/skills/browser-harness/domain-skills"

chown -R node:node "${PAPERCLIP_HOME}" "${HERMES_HOME}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Dispatch on CMD.
# ---------------------------------------------------------------------------
case "${1:-paperclip}" in
    paperclip)
        # First boot only: paperclipai onboard initialises the data dir + db.
        # Run as node since the bundled postgres refuses to start as root.
        if [ ! -d "${PAPERCLIP_HOME}/instances" ]; then
            echo "[entrypoint] first boot — paperclipai onboard --yes --bind ${PAPERCLIP_BIND} --data-dir ${PAPERCLIP_HOME}"
            su -s /bin/bash node -c "
                export HOME='${PAPERCLIP_HOME}' \
                       PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                       HERMES_HOME='${HERMES_HOME}' \
                       PATH='${PATH}'
                paperclipai onboard --yes --bind '${PAPERCLIP_BIND}' --data-dir '${PAPERCLIP_HOME}'
            " || echo "[entrypoint] WARNING: onboard exited non-zero"
        fi

        # Apply PAPERCLIP_EXPOSURE on every boot. paperclipai's onboard hardcodes
        # exposure=private, but for any reverse-proxied deploy you want public
        # (deploymentMode=authenticated still requires login). One-line sed
        # because the field has a fixed JSON shape and there's no CLI for it.
        CFG="${PAPERCLIP_HOME}/instances/default/config.json"
        if [ -f "$CFG" ]; then
            sed -i -E 's|("exposure":[[:space:]]*")[^"]*(")|\1'"${PAPERCLIP_EXPOSURE}"'\2|' "$CFG"
            echo "[entrypoint] config.json server.exposure = ${PAPERCLIP_EXPOSURE}"
        fi

        # Always register PAPERCLIP_DOMAIN in the allowlist if set. This is the
        # canonical fix paperclipai's own error message recommends, and it works
        # regardless of exposure mode — harmless in public, required in private.
        # We do this every boot so a stale volume from an earlier deploy still
        # gets the right hostname registered without manual intervention.
        if [ -n "${PAPERCLIP_DOMAIN:-}" ]; then
            echo "[entrypoint] registering allowed-hostname '${PAPERCLIP_DOMAIN}'"
            su -s /bin/bash node -c "
                export HOME='${PAPERCLIP_HOME}' \
                       PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                       PATH='${PATH}'
                paperclipai allowed-hostname --data-dir '${PAPERCLIP_HOME}' '${PAPERCLIP_DOMAIN}'
            " || echo "[entrypoint] WARNING: allowed-hostname registration failed"
        fi

        # Verification log so failures here are obvious in `docker logs`.
        if [ -f "$CFG" ]; then
            echo "[entrypoint] config.json final state:"
            grep -E '"exposure"|"allowedHostnames"' "$CFG" | sed 's/^/[entrypoint]   /'
        fi

        echo "[entrypoint] starting paperclipai run --bind ${PAPERCLIP_BIND} --data-dir ${PAPERCLIP_HOME} as node on :3100"
        exec su -s /bin/bash node -c "
            export HOME='${PAPERCLIP_HOME}' \
                   PAPERCLIP_HOME='${PAPERCLIP_HOME}' \
                   HERMES_HOME='${HERMES_HOME}' \
                   PATH='${PATH}'
            exec paperclipai run --bind '${PAPERCLIP_BIND}' --data-dir '${PAPERCLIP_HOME}'
        "
        ;;
    hermes)
        # Interactive hermes CLI as node user — sees the same config + skills
        # paperclipai would.
        shift
        exec su -s /bin/bash node -c "
            export HOME='${HERMES_HOME}' \
                   HERMES_HOME='${HERMES_HOME}' \
                   PATH='${PATH}'
            exec hermes $*
        "
        ;;
    *)
        exec "$@"
        ;;
esac
